version: "3.8"
services:
  web:
    build: ./app
    image: 120376859679.dkr.ecr.us-east-1.amazonaws.com/django_docker_web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    Image: 120376859679.dkr.ecr.us-east-1.amazonaws.com/django_docker_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


